[package]
name = "app"
version = "0.1.0"
authors = ["Ryan McGrath <ryan@rymc.io>"]

[dependencies]
libc = "0.2"
objc = "0.2.2"
core-foundation = "0.6.0"
core-graphics = "0.14.0"
cocoa = "0.15.0"
rand = "0.5.0"
im = "10.2.0"
objc_id = "0.1.0"
serde = "*"
serde_json = "*"
